# -*- coding: utf-8 -*-
"""GenSumm-AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MemcXAWrc72W8_yraegcszf-WK84CmtS
"""

!pip install langchain #for langchain  library designed to simplify the process of integrating and using language models
!pip install huggingface_hub #for loading LLM model
!pip install sentence_transformers #for changing sentences to LLM understandable tokens
!pip install faiss-cpu #vector database lib
!pip install PyPDF2 PyPDF #libs for reading PDF file in python
!pip install langchain_community
!pip install PyMuPDF # install the correct library that provides the 'fitz' module
!pip install gtts # Install the missing 'gtts' library

import os #lib which provide various functions for OS related operations, we will use this for setting environment variable programitcally
os.environ["HUGGINGFACEHUB_API_TOKEN"] = "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"

# from langchain.document_loaders import TextLoader  #for textfiles
# from langchain.text_splitter import CharacterTextSplitter #text splitter
# from langchain.document_loaders import UnstructuredPDFLoader  #load pdf
# from langchain.indexes import VectorstoreIndexCreator #vectorize db index with chromadb
# from langchain.chains import RetrievalQA
# from langchain.document_loaders import UnstructuredURLLoader  #load urls into docoument-loader

#LLM
# Vectorstore: https://python.langchain.com/en/latest/modules/indexes/vectorstores.html
from langchain import HuggingFaceHub #for loading LLM
from langchain.embeddings import HuggingFaceEmbeddings #for loading embeddings

#Document Loader
from langchain.document_loaders import PyPDFLoader #for loading pdf files in langchain
from langchain.text_splitter import RecursiveCharacterTextSplitter #for splitting text

#Vector DB
from langchain.vectorstores import FAISS  #facebook AI Similarity Search for vectorization

#Chains
from langchain.chains.question_answering import load_qa_chain #for setting up QnA chain
from langchain.chains import ConversationalRetrievalChain #for setting the conversation chain

from langchain.memory import ConversationBufferMemory #for keeping the context memory in conversation

from google.colab import drive
drive.mount('/content/drive')

loader = PyPDFLoader("/content/drive/MyDrive/RH_StudyGuide_V2.pdf")

pages = loader.load_and_split()
print(pages[0].page_content)

#from langchain.text_splitter import RecursiveCharacterTextSplitter

sections = RecursiveCharacterTextSplitter(
   chunk_size=1000,
   chunk_overlap=100,
   length_function=len).split_documents(pages)

# Embeddings
#from langchain.embeddings import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings()

faiss_index = FAISS.load_local("/content/drive/MyDrive/faiss_index", embeddings,allow_dangerous_deserialization=True) # (Facebook AI Similarity Search) is a library developed by Facebook for efficient similarity search and clustering of high-dimensional vectors.

# expose Vector DB index in a retriever interface
retriever = faiss_index.as_retriever()

#from langchain.memory import ConversationBufferMemory

memory = ConversationBufferMemory(
   memory_key='chat_history',
   return_messages=True,
   output_key='answer')

# Using text2text HF fine-tuned model with 770M parameters
llm=HuggingFaceHub(repo_id="declare-lab/Flan-Alpaca-Large",
                   model_kwargs={"temperature":0.1,
                                 "max_length":512})

#from langchain.chains import ConversationalRetrievalChain

chain = ConversationalRetrievalChain.from_llm(
   llm=llm,
   retriever=retriever,
   memory=memory
)

from pprint import pprint
pprint (memory.buffer)

chain_qa = load_qa_chain(llm,
                         chain_type="stuff",
                         verbose=False)

query = "Who is author of the book?"
docs = faiss_index.similarity_search(query)
chain_qa.run(input_documents=docs, question=query)

query = "What is the name of session one?"
docs = faiss_index.similarity_search(query)
chain_qa.run(input_documents=docs, question=query)

import fitz  # PyMuPDF reading and extracting

def extract_text_from_pdf(pdf_path="/content/drive/MyDrive/RH_StudyGuide_V2.pdf"):
    text = ""
    pdf_document = fitz.open("/content/drive/MyDrive/RH_StudyGuide_V2.pdf")
    for page_num in range(len(pdf_document)):
        page = pdf_document.load_page(page_num)
        text += page.get_text()
    return text

from transformers import pipeline #Text Classification

def summarize_text(text):
  summarizer = pipeline("summarization")
  summary = summarizer(text, max_length=200, min_length=50, do_sample=False)
  return summary[0]['summary_text']

from gtts import gTTS #google translate to text

def convert_text_to_audio(text, audio_path):
    tts = gTTS(text, lang='en')
    tts.save(audio_path)

# Call the function to extract text from the PDF
text = extract_text_from_pdf()

# You may also want to summarize the text before converting to audio
# text = summarize_text(text)

convert_text_to_audio(text, audio_path)

audio_path = "/content/drive/MyDrive/RH_StudyGuide_V2_Audio.mp3"

pip install transformers PyPDF2 torch

from PyPDF2 import PdfReader

# Load the PDF
file_path = '/content/drive/MyDrive/RH_StudyGuide_V2.pdf'  # Replace with the actual file path
reader = PdfReader(file_path)

# Extract text from all pages
pdf_text = ""
for page in reader.pages:
    pdf_text += page.extract_text()

print(pdf_text[:1000])  # Print first 1000 characters of the extracted text

from transformers import MarianMTModel, MarianTokenizer #pre-trained neural network model used for machine translation.

# Load the translation model and tokenizer
model_name = "Helsinki-NLP/opus-mt-en-hi"
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

# Split the text into smaller chunks (to avoid memory issues)
text_chunk = pdf_text[:500]  # Adjust chunk size as needed

# Tokenize and translate
translated_tokens = model.generate(**tokenizer(text_chunk, return_tensors="pt", padding=True))
translated_text = tokenizer.decode(translated_tokens[0], skip_special_tokens=True)

print(translated_text)  # Print the translated text

with open("translated_output.txt", "w", encoding="utf-8") as file:
    file.write(translated_text)

chunk_size = 500  # Define chunk size
translated_text_full = ""

for i in range(0, len(pdf_text), chunk_size):
    text_chunk = pdf_text[i:i + chunk_size]
    translated_tokens = model.generate(**tokenizer(text_chunk, return_tensors="pt", padding=True))
    translated_text_full += tokenizer.decode(translated_tokens[0], skip_special_tokens=True) + "\n"

# Save or print the full translated text
print(translated_text_full)

!pip install streamlit
!pip install  transformers
! pip install  gtts
! pip install PyPDF2
!pip install  langchain
!pip install langchain-community
!pip install pymupdf
!pip install python-dotenv
!pip install chromadb
!pip install sacremoses
!pip install --upgrade streamlit
!pip install --upgrade transformers gtts PyPDF2
!pip install pdfplumber

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from transformers import pipeline, MarianMTModel, MarianTokenizer
# from gtts import gTTS
# import pdfplumber
# import asyncio
# import time
# from concurrent.futures import ThreadPoolExecutor
# 
# # Load models once and cache them
# @st.cache_resource
# def load_models():
#     summarizer = pipeline("summarization", model="facebook/bart-base")  # Use a smaller model for faster performance
#     qa_pipeline = pipeline("question-answering", model="distilbert/distilbert-base-cased-distilled-squad")
#     return summarizer, qa_pipeline
# 
# summarizer, qa_pipeline = load_models()
# 
# # Supported languages and corresponding MarianMT model codes
# LANGUAGE_MODELS = {
#     'Spanish': 'Helsinki-NLP/opus-mt-en-es',
#     'French': 'Helsinki-NLP/opus-mt-en-fr',
#     'German': 'Helsinki-NLP/opus-mt-en-de',
#     'Italian': 'Helsinki-NLP/opus-mt-en-it',
#     'Portuguese': 'Helsinki-NLP/opus-mt-en-pt',
#     'Hindi': 'Helsinki-NLP/opus-mt-en-hi'  # Added Hindi
# }
# 
# # Function to extract text from PDF
# @st.cache_data
# def extract_text_from_pdf(pdf_file):
#     text = ""
#     with pdfplumber.open(pdf_file) as pdf:
#         for page in pdf.pages:
#             text += page.extract_text() or ""
#     return text
# 
# # Function to summarize a chunk of text
# def summarize_chunk(chunk, max_summary_length):
#     try:
#         summary = summarizer(chunk, max_length=max_summary_length, min_length=20, do_sample=False)[0]['summary_text']
#         return summary
#     except Exception as e:
#         st.error(f"Error summarizing chunk: {e}")
#         return ""
# 
# # Asynchronous summarization function with limited concurrency
# async def summarize_text(text, max_chunk_size=1024, max_summary_length=50):
#     chunks = [text[i:i + max_chunk_size] for i in range(0, len(text), max_chunk_size)]
#     with ThreadPoolExecutor(max_workers=4) as executor:
#         loop = asyncio.get_event_loop()
#         summaries = await asyncio.gather(
#             *[loop.run_in_executor(executor, summarize_chunk, chunk, max_summary_length) for chunk in chunks]
#         )
#     return " ".join(summaries)
# 
# # Asynchronous translation function with batch processing
# async def translate_text(text, model_name, chunk_size=1000):
#     translation_model = MarianMTModel.from_pretrained(model_name)
#     tokenizer = MarianTokenizer.from_pretrained(model_name)
# 
#     translated_text_full = ""
#     chunks = [text[i:i + chunk_size] for i in range(0, len(text), chunk_size)]
#     for text_chunk in chunks:
#         try:
#             loop = asyncio.get_event_loop()
#             translated_tokens = await loop.run_in_executor(None, lambda: translation_model.generate(**tokenizer(text_chunk, return_tensors="pt", padding=True, clean_up_tokenization_spaces=True)))
#             translated_text_full += tokenizer.decode(translated_tokens[0], skip_special_tokens=True) + "\n"
#         except Exception as e:
#             st.error(f"Error translating chunk: {e}")
#     return translated_text_full
# 
# # Function to convert text to audio
# def convert_text_to_audio(text, audio_path, lang='es'):
#     try:
#         tts = gTTS(text, lang=lang)
#         tts.save(audio_path)
#     except Exception as e:
#         st.error(f"Error converting text to audio: {e}")
# 
# # Wrapper for asynchronous summarization
# def get_summary(text, max_summary_length):
#     return asyncio.run(summarize_text(text, max_summary_length=max_summary_length))
# 
# # Wrapper for asynchronous translation
# def get_translation(text, model_name):
#     return asyncio.run(translate_text(text, model_name))
# 
# # Streamlit UI
# st.title('PDF Processing and Query Bot Application')
# 
# uploaded_file = st.file_uploader("Choose a PDF file", type="pdf")
# 
# if uploaded_file is not None:
#     with st.spinner("Extracting text from PDF..."):
#         start_time = time.time()
#         text = extract_text_from_pdf(uploaded_file)
#         st.write("**Extracted Text:**")
#         st.text_area("Extracted Text", text, height=300)
#         st.write(f"Extraction Time: {time.time() - start_time:.2f} seconds")
# 
#         if not text.strip():
#             st.error("The extracted text is empty or unreadable. Please check the PDF file.")
#         else:
#             st.write("**Summary Settings**")
#             max_chunk_size = st.slider("Select chunk size for summarization (in characters):", 512, 2048, 1024)
#             max_summary_length = st.slider("Select maximum summary length:", 20, 100, 50)
# 
#             st.write("**Summary:**")
#             with st.spinner("Summarizing text..."):
#                 start_time = time.time()
#                 summary = get_summary(text, max_summary_length=max_summary_length)
#                 st.write(summary)
#                 st.write(f"Summarization Time: {time.time() - start_time:.2f} seconds")
# 
#             # Export Summary Option
#             st.download_button(label="Download Summary", data=summary, file_name="summary.txt")
# 
#             st.write("**Translation Settings**")
#             selected_language = st.selectbox("Choose a target language for translation:", list(LANGUAGE_MODELS.keys()))
# 
#             st.write("**Translation (to selected language):**")
#             with st.spinner(f"Translating text to {selected_language}..."):
#                 start_time = time.time()
#                 translated_text = get_translation(text, LANGUAGE_MODELS[selected_language])
#                 st.text_area(f"Translated Text ({selected_language})", translated_text, height=300)
#                 st.write(f"Translation Time: {time.time() - start_time:.2f} seconds")
# 
#             # Export Translation Option
#             st.download_button(label="Download Translated Text", data=translated_text, file_name=f"translated_text_{selected_language}.txt")
# 
#             # Convert Translated Text to Audio
#             audio_path = "/tmp/translated_output.mp3"
#             lang_code = 'hi' if selected_language == 'Hindi' else 'es'  # Language code for text-to-speech
#             convert_text_to_audio(translated_text, audio_path, lang=lang_code)
#             st.audio(audio_path, format="audio/mp3")
# 
#             # Export Audio Option
#             with open(audio_path, "rb") as audio_file:
#                 st.download_button(label="Download Audio", data=audio_file, file_name="translated_audio.mp3", mime="audio/mp3")
# 
#             st.subheader('Ask a question about the document')
#             user_query = st.text_input("Your question:", "")
# 
#             if st.button('Submit'):
#                 if user_query:
#                     start_time = time.time()
#                     try:
#                         if text.strip() == "":
#                             st.write("The extracted text is empty. Please check the PDF file.")
#                         else:
#                             result = qa_pipeline(question=user_query, context=text)
#                             answer = result.get('answer', 'No answer found.')
#                             elapsed_time = time.time() - start_time
#                             st.write(f"**Answer:** {answer}")
#                             st.write(f"**Query Time:** {elapsed_time:.2f} seconds")
#                     except Exception as e:
#                         st.error(f"Error getting answer: {e}")
#                 else:
#                     st.write("Please enter a question.")
#

! wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

